from fastapi import APIRouter, Depends, HTTPException
from fastapi.responses import HTMLResponse
from sqlalchemy.orm import Session
from sqlalchemy import func
from typing import Optional
from datetime import datetime

from ..database import get_db
from .. import models
from ..auth import get_current_user

router = APIRouter(prefix="/reports", tags=["reports"])


def generate_expense_report_html(
    expenses: list,
    metrics: dict,
    billing_month: str,
    user_name: str
) -> str:
    """Generate HTML expense report."""
    
    # Group expenses by category
    by_category = {}
    for exp in expenses:
        if exp.category not in by_category:
            by_category[exp.category] = []
        by_category[exp.category].append(exp)
    
    category_html = ""
    for category, items in sorted(by_category.items()):
        total = sum(e.amount for e in items)
        items_html = "".join([
            f'<tr><td style="padding:8px;border-bottom:1px solid #eee">{e.description}</td>'
            f'<td style="padding:8px;border-bottom:1px solid #eee;text-align:right">₹{e.amount:,.2f}</td>'
            f'<td style="padding:8px;border-bottom:1px solid #eee">{e.status}</td></tr>'
            for e in items
        ])
        category_html += f'''
        <div style="margin-bottom:20px">
            <h3 style="color:#4f46e5;border-bottom:2px solid #4f46e5;padding-bottom:5px">{category}</h3>
            <table style="width:100%;border-collapse:collapse">
                <thead><tr style="background:#f3f4f6">
                    <th style="padding:10px;text-align:left">Description</th>
                    <th style="padding:10px;text-align:right">Amount</th>
                    <th style="padding:10px;text-align:left">Status</th>
                </tr></thead>
                <tbody>{items_html}</tbody>
                <tfoot><tr style="background:#e5e7eb;font-weight:bold">
                    <td style="padding:10px">Category Total</td>
                    <td style="padding:10px;text-align:right">₹{total:,.2f}</td>
                    <td></td>
                </tr></tfoot>
            </table>
        </div>
        '''
    
    html = f'''<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>Expense Report - {billing_month}</title>
    <style>
        body {{ font-family: 'Segoe UI', Arial, sans-serif; margin: 40px; color: #1f2937; }}
        .header {{ background: linear-gradient(135deg, #4f46e5, #7c3aed); color: white; padding: 30px; border-radius: 10px; margin-bottom: 30px; }}
        .summary {{ display: grid; grid-template-columns: repeat(4, 1fr); gap: 20px; margin-bottom: 30px; }}
        .summary-card {{ background: #f9fafb; padding: 20px; border-radius: 10px; text-align: center; box-shadow: 0 2px 4px rgba(0,0,0,0.05); }}
        .summary-card h4 {{ margin: 0; color: #6b7280; font-size: 14px; }}
        .summary-card p {{ margin: 10px 0 0; font-size: 24px; font-weight: bold; color: #1f2937; }}
        .footer {{ margin-top: 40px; padding-top: 20px; border-top: 1px solid #e5e7eb; text-align: center; color: #6b7280; font-size: 12px; }}
        @media print {{ body {{ margin: 20px; }} .header {{ -webkit-print-color-adjust: exact; }} }}
    </style>
</head>
<body>
    <div class="header">
        <h1 style="margin:0">📊 Expense Report</h1>
        <p style="margin:10px 0 0;opacity:0.9">{billing_month} | {user_name}</p>
    </div>
    
    <div class="summary">
        <div class="summary-card">
            <h4>Total Expenses</h4>
            <p>₹{metrics.get('total', 0):,.2f}</p>
        </div>
        <div class="summary-card">
            <h4>Paid</h4>
            <p style="color:#10b981">₹{metrics.get('paid', 0):,.2f}</p>
        </div>
        <div class="summary-card">
            <h4>Unpaid</h4>
            <p style="color:#ef4444">₹{metrics.get('unpaid', 0):,.2f}</p>
        </div>
        <div class="summary-card">
            <h4>Expense Count</h4>
            <p>{len(expenses)}</p>
        </div>
    </div>
    
    <h2 style="color:#1f2937;margin-bottom:20px">Expenses by Category</h2>
    {category_html}
    
    <div class="footer">
        <p>Generated by Expensy on {datetime.now().strftime("%B %d, %Y at %I:%M %p")}</p>
        <p>This is an automatically generated report. Print or save as PDF using your browser's print function (Ctrl+P).</p>
    </div>
</body>
</html>'''
    return html


@router.get("/monthly/{billing_month}", response_class=HTMLResponse)
def get_monthly_report(
    billing_month: str,
    db: Session = Depends(get_db),
    current_user: models.User = Depends(get_current_user)
):
    """Generate monthly expense report as printable HTML (use browser Print to save as PDF)."""
    
    # Get expenses for the month
    expenses = db.query(models.Expense).filter(
        models.Expense.user_id == current_user.id,
        models.Expense.billing_month == billing_month
    ).order_by(models.Expense.category, models.Expense.amount.desc()).all()
    
    # Calculate metrics
    total = sum(e.amount for e in expenses)
    paid = sum(e.amount for e in expenses if e.status == "Paid")
    unpaid = sum(e.amount for e in expenses if e.status == "Unpaid")
    
    metrics = {
        "total": total,
        "paid": paid,
        "unpaid": unpaid
    }
    
    html = generate_expense_report_html(expenses, metrics, billing_month, current_user.name)
    return HTMLResponse(content=html)


@router.get("/summary")
def get_report_summary(
    start_month: Optional[str] = None,
    end_month: Optional[str] = None,
    db: Session = Depends(get_db),
    current_user: models.User = Depends(get_current_user)
):
    """Get summary statistics for reporting."""
    
    query = db.query(models.Expense).filter(models.Expense.user_id == current_user.id)
    
    if start_month:
        query = query.filter(models.Expense.billing_month >= start_month)
    if end_month:
        query = query.filter(models.Expense.billing_month <= end_month)
    
    expenses = query.all()
    
    # Group by category
    by_category = {}
    for exp in expenses:
        if exp.category not in by_category:
            by_category[exp.category] = {"count": 0, "total": 0, "paid": 0}
        by_category[exp.category]["count"] += 1
        by_category[exp.category]["total"] += exp.amount
        if exp.status == "Paid":
            by_category[exp.category]["paid"] += exp.amount
    
    # Group by month
    by_month = {}
    for exp in expenses:
        if exp.billing_month not in by_month:
            by_month[exp.billing_month] = {"count": 0, "total": 0}
        by_month[exp.billing_month]["count"] += 1
        by_month[exp.billing_month]["total"] += exp.amount
    
    return {
        "total_expenses": len(expenses),
        "total_amount": sum(e.amount for e in expenses),
        "by_category": by_category,
        "by_month": dict(sorted(by_month.items())),
        "date_range": {
            "start": start_month,
            "end": end_month
        }
    }
